services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test_practice
    ports: ["5432:5432"]
