spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/flowgate_account
    username: dev
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

# JWT 설정
jwt:
  secret: your-secret-key-change-this-in-production-min-256-bits
  expiration: 86400000 # 24시간 (밀리초)
  refresh-expiration: 604800000 # 7일 (밀리초)
