spring:
  application:
    name: ticket-service

  datasource:
    url: jdbc:postgresql://localhost:5432/flowgate_ticket
    username: dev
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# JWT 설정 (account-service와 동일한 secret 사용)
jwt:
  secret: your-secret-key-change-this-in-production-min-256-bits
